global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          instance: sshali

  - job_name: hamr-api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["hamr-api-gateway:8090"]
        labels:
          service: api-gateway
