networks:
  hamr-net:
    driver: bridge
    name: hamr-net

services:
  hamr-developer:
    image: hamr-developer:latest
    container_name: hamr-developer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8200:80"
    networks:
      - hamr-net

  hamr-docs:
    image: hamr-docs:latest
    container_name: hamr-docs
    restart: unless-stopped
    ports:
      - "127.0.0.1:8201:80"
    networks:
      - hamr-net

  hamr-deploy:
    image: hamr-deploy:latest
    container_name: hamr-deploy
    restart: unless-stopped
    ports:
      - "127.0.0.1:8202:80"
    networks:
      - hamr-net
